### ISSUE TITLE
Update version of Meteor and README.md with updated instructions

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/fireball#11]

**Comment by saksham15082** [comment]
Can you please help me.I would like to contribute to open source and it is my first time.Can i contribute to this issue?

**Comment by lynnaloo** [comment]
This project is using a really old version of the JavaScript framework Meteor.js: https://www.meteor.com/. In this issue, I'd like to have someone update this to work with the latest version. I'm not sure what is entirely involved in this because I haven't kept up with Meteor, but their documentation should give you a walk-through.

**Comment by saksham15082** [comment]
Sorry i am a beginner and dont know javascript and would like to opt out.Thanks.

**Comment by lynnaloo** [comment]
@saksham15082 Checkout my `oranjs` repository for more beginner-friendly issues.

**Comment by dustinsharp** [comment]
@lynnaloo I'd like to claim this one.

**Comment by lynnaloo** [comment]
👍

**Comment by dustinsharp** [comment]
Should the project itself be modified to use some of the new features of Meteor (like what's laid out in https://www.meteor.com/tutorials/blaze/creating-an-app) or to simply be able to run on the newest Meteor version.

**Comment by lynnaloo** [comment]
I think it would be really cool to use some new features of Meteor, but at a min make sure it works with the new version.

**Comment by dustinsharp** [comment]
Alright, I have it working with Meteor 1.4. I'll see what I can do about adding some of the new features.

**Comment by lynnaloo** [comment]
Do you want to PR to the README with those changes and do any of the other new features separately?

**Comment by dustinsharp** [comment]
Sure. The README PR will most likely not have very many changes on how to get the project up and running. The README change would just be updating the portion about the deployment. Meteor changed to that to where you have to have a Galaxy account with them in order to deploy to their server. With that in mind, are you alright with separate PRs?
